[phases.setup]
nixPkgs = [
  "python38",
  "gcc",
  "unixODBC",
  "mssql-tools"
]

[phases.install]
cmds = [
  "python -m venv /opt/venv",
  ". /opt/venv/bin/activate",
  "pip install --no-cache-dir -r requirements.txt"
]

[start]
cmd = "python temp_api.py"