[phases.setup]
packages = ["python38", "gcc", "unixODBC", "curl", "gnupg2", "build-essential"]

[phases.install]
commands = [
    "python3 -m venv /opt/venv",
    "/opt/venv/bin/pip install --no-cache-dir -r requirements.txt"
]

[phases.build]
commands = []  # nothing to build

[phases.start]
commands = [
    "/opt/venv/bin/python temp_api.py"
]

[env]
PATH = "/opt/venv/bin:$PATH"
