[phases.setup]
# system dependencies
packages = ["python38", "gcc", "unixODBC", "curl", "gnupg2", "build-essential"]

[phases.install]
# create virtual environment and install dependencies
commands = [
    "python3 -m venv /opt/venv",
    ". /opt/venv/bin/activate",
    "pip install --no-cache-dir -r requirements.txt"
]

[phases.build]
# nothing to build for Flask
commands = []

[phases.start]
# start Flask app with venv activated
commands = [
    ". /opt/venv/bin/activate",
    "python temp_api.py"
]

[env]
PATH = "/opt/venv/bin:$PATH"
