[phases.setup]
packages = ["python38", "gcc", "unixODBC", "curl", "gnupg2", "build-essential"]

[phases.install]
# Use venv and install Python dependencies
commands = [
    "python3 -m venv /opt/venv",
    ". /opt/venv/bin/activate",
    "pip install --no-cache-dir -r requirements.txt"
]

[phases.build]
# Optional: can leave empty if no build needed
commands = []

[phases.start]
# Start Flask app
commands = ["python temp_api.py"]

[env]
# Ensure Python venv is used
PATH = "/opt/venv/bin:$PATH"
